Cart/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homepage
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name='homepage'),
    path('store/', include('products.urls')),
    path('cart/', include('clothes_cart.urls')),
    path('account/', include('custom_user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.safestring import mark_safe

from categories.models import Category


# Create your models here.

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    product_description = models.TextField(max_length=600, blank=True)
    price = models.FloatField()
    old_price = models.FloatField(null=True)
    image = models.ImageField(upload_to='photos/products')
    quantity = models.IntegerField()
    is_available = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def image_img(self):
        if self.image:
            return mark_safe(u'<a href="{0}" target="_blank"><img src="{0}" width="100"/></a>'.format(self.image.url))
        else:
            return 'No image'

    image_img.short_description = 'Main Image'
    image_img.allow_tags = True

    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name


parameters_variations = [
    ['color', 'color'],
    ['size', 'size']
]


class ParameterManager(models.Manager):

    def color(self):
        return super(ParameterManager, self).filter(category_param='color', is_available=True)

    def size(self):
        return super(ParameterManager, self).filter(category_param='size', is_available=True)


class Parameter(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category_param = models.CharField(max_length=30, choices=parameters_variations, blank=True)
    value_param = models.CharField(max_length=80)
    created_date = models.DateTimeField(auto_now_add=True)
    is_available = models.BooleanField(default=True)
    manager_param = ParameterManager()

    def __str__(self):
        return self.value_param

Cart/views.py
from django.shortcuts import render
from products.models import Product

def homepage(request):
    products = Product.objects.all().filter(is_available=True)
    context = {
        'products': products
    }
    return render(request, 'homepage.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}
	<h3 class="text-center">Your cart is empty</h3>
	<br>
	<div class="text-center">
		<a href="{% url 'store' %}" class="btn btn-primary">Go shopping</a>

	</div>

	{% else %}
<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>
{% for item in cart_items %}
<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ item.product.image.url }}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ item.product.get_url }}" class="title text-dark">{{ item.product.product_name }}</a>
				<p class="text-muted small">
					{% if item.parameters.all %}
					{% for val in item.parameters.all %}
					{{ val.category_param }}: {{ val.value_param }}
				{% endfor %}
				{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
					<div class="col">
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href="{% url 'remove_item_from_cart' item.product.id item.id %}"class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{ item.quantity }}">
							<div class="input-group-append"><form action="">
							<a href="{% url 'add_to_cart' item.product.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-plus"></i> </a>
							</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">{{ item.product_total_price }} $</var>
			<small class="text-muted"> {{ item.product.price }} $ each </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right">
	<a href="{% url 'delete_from_cart' item.product.id item.id %}" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}
</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">{{ total }} $</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> {{ tax }}$</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Total:</dt>
			  <dd class="text-right text-dark b"><strong>{{ tax_total }} $</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="{% url 'checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
	{% endif %}
</div> <!-- container .//  -->
</section>

{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap">
	   <a href="#"><img src="{{ single_product.image.url }}"></a>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">
		<form action=" {% url 'add_to_cart' single_product.id %}" method="POST" >
			{% csrf_token %}
			<article class="content-body">

			<h2 class="title">{{ single_product.product_name }}</h2>

			<div class="mb-3">
				<var class="price h4">{{ single_product.price }} $</var>
			</div>

			<p>{{ single_product.product_description }}</p>


			<hr>
				<div class="row">
					<div class="item-option-select">
						<h6>Color</h6>
						<select name="color" class="form-control" required>
							<option value=""disabled selected> Select color</option>
							{% for value in single_product.parameter_set.color %}
							<option value="{{ value.value_param | lower}}">{{value.value_param | capfirst}}</option>
							{% endfor %}
						</select>
					</div>
				</div> <!-- row.// -->
				<div class="row">
					<div class="item-option-select">
						<h6>Size</h6>
						<select name="size" class="form-control">
							<option value=""disabled selected> Select size</option>
							{% for value in single_product.parameter_set.size %}
							<option value="{{ value.value_param | lower}}">{{value.value_param | capfirst}}</option>
							{% endfor %}
						</select>

					</div>
				</div> <!-- row.// -->
				<hr>
				{% if single_product.quantity <= 0 %}
				<h5> Out of stock </h5>
				{% else %}
					<button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
				{% endif %}
			</article> <!-- product-info-aside .// -->
		</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3> Reviews </h3>

	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">18.01.2023 </span>
				<h6 class="mb-1">Luiza Dalles </h6>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
				Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip
			</p>
		</div>
	</article>



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/store.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
<div class="container">
	{% if 'search' in request.path %}
	<h2 class="title-page">Result</h2>
	{% else %}
	<h2 class="title-page">Our Store</h2>
	{% endif %}
</div> <!-- container //  -->
</section>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">

<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">
				<ul class="list-menu">
					<li><a href="{% url 'store' %}"> All Clothes </a></li>
					{% for category in links %}
					<li><a href="{{ category.get_url }}">{{ category.cat_name }}</a></li>
					{% endfor %}
				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Sizes </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_4" style="">
			<div class="card-body">
			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XS </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> SM </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> LG </span>
			  </label>

			  <label class="checkbox-btn">
			    <input type="checkbox">
			    <span class="btn btn-light"> XXL </span>
			  </label>
		</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">

				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">$0</option>
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">$50</option>
						<option value="100">$100</option>
						<option value="150">$150</option>
						<option value="200">$200</option>
						<option value="500">$500</option>
						<option value="1000">$1000</option>
						<option value="2000">$2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto">Found {{ product_count }} items </span>

		</div>
</header><!-- sect-heading -->
<div class="row">
	{% if not products %}
	<div>
		<h2>Nothing found</h2>
	</div>
	{% else %}
	{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap">

				<a href="{{ product.get_url }}"><img src="{{ product.image.url }}"></a>

			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{ product.get_url }}" class="title">{{ product.product_name }}</a>
					<div class="price-wrap mt-2">
						<span class="price">{{ product.price }} $</span>
						<del class="price-old">{{ product.old_price }} $</del>
					</div> <!-- price-wrap.// -->
				</div>
				{% if product.quantity <= 0 %}
				<h5> Out of stock </h5>
				{% else %}
				<a href="{{ product.get_url }}" class="btn btn-block btn-primary"> Details </a>
				{% endif %}
			</figcaption>
		</figure>
	</div> <!-- col.// -->

	{% endfor %}
	{% endif %}
</div> <!-- row end.// -->


<nav class="mt-4" aria-label="Page navigation sample">
	{% if products.has_other_pages %}
  <ul class="pagination">
	  {% if products.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
	  {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
	  {% endif %}
	  {% for page in products.paginator.page_range %}
	  {% if products.number == page %}
    	<li class="page-item active"><a class="page-link" href="{{ page.number }}">{{ page }} </a></li>
	  {% else %}
    	<li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }} </a></li>
	  {% endif %}
	  {% endfor %}
	  {% if products.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
	  {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
	  {% endif %}
  </ul>
	{% endif %}
</nav>

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>

{% endblock %}